language: ruby
rvm:
 - "2.0.0"
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
services:
 - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
env:
  global:
    - cloud_name=demo
