---
development:
  cloud_name: <%= ENV["CLOUD_NAME_CLOUDINARY"] %>
  api_key: <%= ENV["API_KEY_CLOUDINARY"] %>
  api_secret: <%= ENV["API_SECRET_CLOUDINARY"] %>
  enhance_image_tag: true
  static_image_support: false
test:
  cloud_name: <%= ENV["CLOUD_NAME_CLOUDINARY"] %>
  api_key: <%= ENV["API_KEY_CLOUDINARY"] %>
  api_secret: <%= ENV["API_SECRET_CLOUDINARY"] %>
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: <%= ENV["CLOUD_NAME_CLOUDINARY"] %>
  api_key: <%= ENV["API_KEY_CLOUDINARY"] %>
  api_secret: <%= ENV["API_SECRET_CLOUDINARY"] %>
  enhance_image_tag: true
  static_image_support: true
