# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e247ef94d7c020ff916b1818c0e81806becbe69992ce7b20d6c481dee75c35d7660f4ccdfc9f201a88c959d13681d1c62a422cc764b5ad25559ee4b541505e4a

test:
  secret_key_base: 59cabe8529ee3975b723844d0cdd47394fe250c7176ae47dbe26244812568bbae1dd68bee114ad44d65a50323dff56440511a7ac906a0eb853e6cae3670a1c46

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
